### PR TITLE
Update runtime to GNOME 42

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
build failure is caused by an invalid translation file. And it is like the same build failure as on master.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
this was fixed locally and it fail again ? *sigh*

**Comment by hfiguiere** [comment]
oh I see, I apparetly forgot to check-in the change in the manifest that add the patch....

**Comment by carlos157oliveira** [comment]
This is different. I wasn't aware that one could patch files in the flatpak JSON declaration. How does it work?

**Comment by hfiguiere** [comment]
see commit 1a909ce

**Comment by hfiguiere** [comment]
also using PR before pushing update allow making sure it work instead of having the build silently fail on master.

**Comment by carlos157oliveira** [comment]
Thank you for your help. I am merging it.

**Pull request merged**
